### ISSUE TITLE
Feature Request: Modern looking Window Hints

### ISSUE THREAD

**Issue by DeadlySquad13** [sindrets/winshift.nvim#10]
Hello!
Thanks for your plugin! I've found it particularly useful in my workflow. However, the feature I use the most is swapping windows and window hints are barely visible which leads to an eyestrain during the day.
![image](https://user-images.githubusercontent.com/46250621/173897784-24017013-60b9-4aa1-ac57-0ca0b971832a.png)

Would you be so kind to implement custom callback option for showing hints / make some options for their customization?

As for me, the best way is to completely reimplement it using newer vim features - floating windows. It would look like this:
![image](https://user-images.githubusercontent.com/46250621/173898531-489eaff1-3381-43bb-b9f4-5332de8f752e.png)
(screenshot using complementary plugin [nvim-window](https://gitlab.com/yorickpeterse/nvim-window/-/tree/main))

**Comment by sindrets** [comment]
@DeadlySquad13 I personally like the minimal window picker as it is, but I could make the window picker configurable by letting users provide their own function.

>  window hints are barely visible which leads to an eyestrain during the day.

Hm, I don't think you're doing yourself any favors in terms of readability by making the window picker highlights the same as your Normal background + foreground. The default highlights for the window picker stand out a lot more.
