### ISSUE TITLE
allow ignoring certain filetypes in the config

### ISSUE THREAD

**Issue by NotAShelf** [sindrets/winshift.nvim#15]
I think `filter_func` is meant to be the more extensive alternative to ignoring filetypes, but I can't seem to get it to work with NvimTree (and Alpha, which just blinks the screen).

Perhaps we could have a config option to ignore certain filetypes directly, without a filter?

**Comment by sindrets** [comment]
https://github.com/sindrets/winshift.nvim/blob/37468ed6f385dfb50402368669766504c0e15583/doc/winshift.txt#L74

**Comment by NotAShelf** [comment]
I was hoping that would work, but it seems either 'NvimTree' and 'Alpha' are not valid filetypes, or I am missing something out.

**Comment by sindrets** [comment]
Alpha's filetype is `alpha`, all lowercase. Capitalization matters in the filter rules. Don't know what filetype nvim-tree uses as I haven't used it in a long time. But you can easily find out by focusing a nvim-tree buffer and running:

```
:echo &ft
```

**Comment by sindrets** [comment]
I'm gonna consider this issue as resolved. Let me know if anything is still unclear.
