### ISSUE TITLE
WinShift repeats message when pressing other keys

### ISSUE THREAD

**Issue by sayit358** [sindrets/winshift.nvim#2]
If I call `:WinShift` and press any key other than <kbd>h</kbd>, <kbd>j</kbd>, <kbd>k</kbd>, <kbd>l</kbd>, <kbd>q</kbd>, and <kbd>Esc</kbd>, the prompt duplicates itself like this:

```
-- WIN MOVE MODE -- press 'q' to exit
-- WIN MOVE MODE -- press 'q' to exit
```

I'd also like to thank you for this plugin. It's very nice! :heart:

**Comment by sindrets** [comment]
Glad to hear you like it!

Fixed via e392fd5b3ca0ef8279a8230129695fc7a921f4c3.
